name = "vpn-config-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 * * * *"]

[vars]
BOT_TOKEN = ""
ADMIN_CHAT_ID = ""
CHANNEL_ID = ""
DASHBOARD_USER = ""
DASHBOARD_PASS = ""

[[kv_namespaces]]
binding = "VPN_CACHE"
id = ""
